BREEDS = [
    "Labrador Retriever",
    "Golden Retriever",
    "German Shepherd",
    "French Bulldog",
    "Bulldog",
    "Poodle",
    "Beagle",
    "Rottweiler",
    "Dachshund",
    "Siberian Husky",
    "Boxer",
    "Doberman Pinscher",
    "Great Dane",
    "Shih Tzu",
    "Border Collie",
    "Australian Shepherd",
    "Pembroke Welsh Corgi",
    "Cavalier King Charles Spaniel",
    "Boston Terrier",
    "Shetland Sheepdog",
    "Bernese Mountain Dog",
    "Miniature Schnauzer",
    "Cocker Spaniel",
    "Chihuahua",
    "Bichon Frise",
    "Pug",
    "Akita",
    "Maltese",
    "Saint Bernard",
    "Havanese",
    "Belgian Malinois",
    "Weimaraner",
    "English Springer Spaniel",
    "Bloodhound",
    "Irish Setter",
    "Alaskan Malamute",
    "Airedale Terrier",
    "Lhasa Apso",
    "American Staffordshire Terrier",
    "Basenji",
    "Whippet",
    "Newfoundland",
    "Cane Corso",
    "Yorkshire Terrier",
    "Scottish Terrier",
    "Chinese Crested",
    "Papillon",
    "Brussels Griffon",
    "Italian Greyhound",
    "Samoyed",
]
